# Generated by Django 3.2.3 on 2021-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_files_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='files',
            name='document',
            field=models.FileField(upload_to='files/'),
        ),
    ]
